language: objective-c
osx_image: xcode7.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8

before_install:
  - brew update

script:
  - xcodebuild test -scheme GetBSDProcessListTests -configuration Release
  - carthage build --no-skip-current

notifications:
  email: false
